<?php 
    $this->headLink()->appendStylesheet($this->baseUrl('/css/jquery-ui/jquery-ui.css'));
    
    $this->headScript()->appendFile($this->baseUrl('/js/jquery-ui/jquery-ui.js'))
                       ->appendFile($this->baseUrl('/js/jquery-ui/datepicker-ar.js'));
?>

<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Make New Payment') ?></h3>
    </div>
    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item list-group-item-info">
                <div class="">
                    <strong><?php echo $this->translate('Name') ?>: </strong>
                    <?php echo $this->client['clientName'] ?>
                </div>
                <div class="">
                    <strong><?php echo $this->translate('Balance') ?>: </strong>
                    <?php echo $this->client['clientBalance'] ?>
                </div>
            </li>
            <div>
                <?php echo $this->form ?>
            </div>
            <li class="list-group-item">
                <a href="<?php echo $this->baseUrl() . '/client/view/id/' . $this->client['clientId'] ?>" class="btn btn-warning col-xs-offset-3">
                    <?php echo $this->translate('Back to Client') ?>
                </a>
            </li>
        </ul>
    </div>
</div>

<script>
    $(function() {
        $.datepicker.setDefaults( $.datepicker.regional[ "ar" ] );
        $( "#paymentDatepicker" ).datepicker({
            dateFormat: "yy-mm-dd",
            onSelect: function(date){
                $( "#paymentDate" ).val(date);
            }
        });
    });
</script>
<style>
    .ui-datepicker{
        width: 14em !important;
        font-size: 0.74em;
    }
</style>