<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        <!--
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
        -->
    </head>
    <body>
        	
        <div class="se-pre-con"></div>
        
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand brand-style" href="<?php echo $this->baseUrl();?>"><?php echo $this->translate('iCount')?></a>
            </div>
            <!-- /.navbar-header -->
        </nav>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2 navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li>
                                <a href="<?php echo $this->baseUrl() . '/client' ?>">
                                    <i class="fa fa-group fa-fw"></i> <?php echo $this->translate('Clients') ?>
                                    <span class="fa arrow"></span>
                                </a>
                                <ul class="nav nav-second-level">
                                    <?php foreach ($this->navGroups as $group) { ?>
                                    <li>
                                        <a href="<?php echo $this->baseUrl().'/client/group/id/'.$group['groupId'] ?>">
                                            <i class="fa fa-star-o fa-fw"></i><?php echo $group['groupName'] ?>
                                        </a>
                                    </li>
                                    <?php } ?>
                                    <li>
                                        <a href="<?php echo $this->baseUrl().'/client/add' ?>">
                                            <i class="fa fa-plus-square-o fa-fw"></i><?php echo $this->translate('Add New Client') ?>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->baseUrl().'/client/search' ?>">
                                            <i class="fa fa-search fa-fw"></i><?php echo $this->translate('Find Client') ?>
                                        </a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <!--
                            <li>
                                <a href="#">
                                    <i class="fa fa-sitemap fa-fw"></i> <?php echo $this->translate('Groups') ?>
                                    <span class="fa arrow"></span>
                                </a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="<?php echo $this->baseUrl().'/group' ?>">
                                            <i class="fa fa-list fa-fw"></i><?php echo $this->translate('Display Groups') ?>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->baseUrl().'/group/add' ?>">
                                            <i class="fa fa-plus-square-o fa-fw"></i><?php echo $this->translate('Add New Group') ?>
                                        </a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            
                            <li>
                                <a href="<?php echo $this->baseUrl().'/report' ?>">
                                    <i class="fa fa-line-chart fa-fw"></i> <?php echo $this->translate('Reports') ?>
                                </a>
                            </li>
                            
                            <li>
                                <a href="<?php echo $this->baseUrl().'/auth/logout'?>">
                                    <i class="fa fa-sign-out fa-fw"></i> <?php echo $this->translate('Logout') ?>
                                </a>
                            </li>
                            
                            <!--
                            <li>
                                <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Forms</a>
                            </li>
                            -->
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
                
                <div class="col-sm-9">
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
    </body>
</html>