<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Groups List') ?></h3>
    </div>
    <div class="panel-body">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php echo $this->translate('Name') ?></th>
                    <!--<th><?php echo $this->translate('Actions') ?></th>-->
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->groups as $group) {?>
                <tr>
                    <td><?php echo $group['groupId'] ?></td>
                    <td>
                        <a href="<?php echo $this->baseUrl() . '/group/edit/id/' . $group['groupId'] ?>">
                            <?php echo $group['groupName'] ?>
                        </a>
                    </td>
                    <!--<td></td>-->
                </tr>
                <?php }?>
            </tbody>
        </table>
    </div>
</div>