<div id="accountPanel" class="panel-scroll">
    <ul class="list-group">
        <li class="list-group-item list-group-item-danger">
            <div class="">
                <strong><?php echo $this->translate('Tab any statement row to edit') ?></strong>
            </div>
        </li>
    </ul>
    <table class="table table-bordered table-condensed table-statement">
        <thead>
            <tr class="active">
                <th><?php echo $this->translate('Statement') ?></th>
                <th><?php echo $this->translate('Price') ?></th>
                <th><?php echo $this->translate('Paid') ?></th>
                <th><?php echo $this->translate('Remaining') ?></th>
                <th><?php echo $this->translate('Date') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php if($this->client['clientBalance']){?>
            <tr class="warning">
                <td><?php echo $this->translate('Goods') ?></td>
                <td><?php echo $this->client['clientBalance'] ?></td>
                <td>-</td>
                <td><?php echo $this->client['clientBalance'] ?></td>
                <td>-</td>
            </tr>
            <?php }?>
            <?php if(count($this->fullStatement)) {
                    $totalGoods = $this->client['clientBalance'];
                    $totalPaid = 0;
                    $remaining = 0;
            ?>
                <?php foreach ($this->fullStatement as $statement){
                    $totalGoods += $statement['statementPrice'];
                    $totalPaid += $statement['statementPaid'];
                    $remaining += $statement['statementPrice'] - $statement['statementPaid'];
                ?>
                <tr class="clickable-row <?php echo ($statement['statementDescription']) ? 'warning' : '' ?>" 
                    data-href="<?php echo $this->baseUrl('/'.$statement['statementType'].'/edit/id/'.$statement['statementId']) ?>">
                    <td><?php echo ($statement['statementDescription'])? $statement['statementDescription'] : '-' ?></td>
                    <td><?php echo ($statement['statementPrice'])? $statement['statementPrice'] : '-' ?></td>
                    <td><?php echo ($statement['statementPaid'])? $statement['statementPaid'] : '-' ?></td>
                    <td><?php echo $this->client['clientBalance'] + $remaining ?></td>
                    <td><?php echo date_format(new DateTime($statement['statementDate']), 'm/d') ?></td>
                </tr>
                <?php }?>
                <tr>
                    <td><?php echo $this->translate('') ?></td>
                    <td class="info"><strong><?php echo $totalGoods ?></strong></td>
                    <td class="success"><strong><?php echo $totalPaid ?></strong></td>
                    <td class="danger"><strong><?php echo $this->client['clientBalance'] + $remaining ?></strong></td>
                    <td></td>
                </tr>
            <?php } else {?>
                <tr class="">
                    <td colspan="5"><?php echo $this->translate('There is no statements yet') ?></td>
                </tr>
            <?php }?>
        </tbody>
    </table>
</div>
<div class="margin-20">
    <a href="<?php echo $this->baseUrl() .  '/client/view/id/' . $this->client['clientId'] ?>" class="btn btn-danger">
        <?php echo $this->translate('Cancel and Return') ?>
    </a>
</div>

<script>
    jQuery(document).ready(function($) {
        $(".clickable-row").click(function() {
            window.document.location = $(this).data("href");
        });
    });
</script>