<div class="panel panel-info panel-info-client">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->client['clientName'] ?></h3>
    </div>
    <div class="panel-body">
        
        <div role="tabpanel">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs client-tabs" role="tablist">
                <li role="presentation" class="active">
                    <a href="#full-statement" aria-controls="full-statement" role="tab" data-toggle="tab">
                        <?php echo $this->translate('Page') ?>
                        <span class="badge"><?php echo $this->client['clientPageNumber'] ?></span>
                    </a>
                </li>
            </ul>
            
            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="full-statement">
                    <?php echo $this->partial('statement/editable-view.phtml', array('client'=>$this->client, 'fullStatement'=>$this->fullStatement)); ?>
                </div>
            </div>
            
        </div>
        <div class="panel-footer">
            <div class="">
                <a href="<?php echo $this->baseUrl() .  '/client/group/id/' . $this->client['clientGroup'] ?>" class="btn btn-default">
                    <?php echo $this->translate('Back to Client List') ?>
                </a>
            </div>
        </div>
        
    </div>
</div>