<div class="panel panel-warning">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Edit Client') ?></h3>
    </div>
    <div class="panel-body">
        <?php echo $this->form ?>
    </div>
    <ul class="list-group">
        <li class="list-group-item">
            <a href="<?php echo $this->baseUrl() . '/client/view/id/' . $this->client['clientId'] ?>" class="btn btn-warning col-xs-offset-3">
                <?php echo $this->translate('Back to Client') ?>
            </a>
        </li>
    </ul>
</div>