<div class="panel panel-warning">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Edit Client') ?></h3>
    </div>
    <div class="panel-body">
        <?php echo $this->form ?>
    </div>
    <div class="panel-footer">
        <div class="">
            <a href="<?php echo $this->baseUrl() .  '/client/view/id/' . $this->client['clientId'] ?>" class="btn btn-default">
                <?php echo $this->translate('Back to Client') ?>
            </a>
        </div>
    </div>
</div>