<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">
            <?php echo ( isset($this->panelTitle) ) ? $this->panelTitle : $this->group['groupName'] ?>
        </h3>
    </div>
    <div class="panel-body">
        <div  class="">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                        <!-- List Header -->
                        <div class="panel-client">
                            <div class="panel-heading" id="heading-0">
                                <h4 class="panel-title">
                                    <div  class="btn btn-client btn-client-heading">
                                        <strong><?php echo $this->translate('Client') ?></strong> 
                                        <span><i class="fa fa-bar-chart fa-fw"></i></span>
                                    </div>
                                </h4>
                            </div>
                        </div>
                
                <?php if(count($this->clients)) {?>
                    <?php foreach ($this->clients as $client) {?>
                
                        <div class="panel panel-client">
                            <div class="panel-heading" role="tab" id="heading-<?php echo $client['clientId'] ?>">
                                <h4 class="panel-title">
                                    <a  class="btn btn-default btn-client"
                                        data-toggle="collapse" 
                                        data-parent="#accordion" 
                                        href="#client-<?php echo $client['clientId'] ?>" 
                                        aria-expanded="true" 
                                        aria-controls="client-<?php echo $client['clientId'] ?>">
                                        
                                        <strong><?php echo $client['clientName'] ?></strong>
                                        <span><strong><?php echo $client['clientPageNumber'] ?></strong> <i class="fa fa-file-text-o"></i></span>
                                        
                                        <div class="">
                                            <?php echo $this->translate('Balance') ?> 
                                            <?php if($client['lastPaid']){
                                                        $date = explode('/', date_format(new DateTime($client['lastPaid']), 'm/d'));
                                                        $date[0] = sprintf("%d", $date[0]);
                                                        $date[1] = sprintf("%d", $date[1]);
                                                        echo $client['lastPaid'] = implode('/', $date);
                                                  } else {
                                                        echo '-';
                                                  }
                                            ?>
                                            <span class="label label-balance">
                                                <?php echo $client['clientBalance'] + $client['clientGoods'] - $client['clientPaid'] ?>
                                            </span>
                                        </div>
                                    </a>
                                </h4>
                            </div>
                            <div id="client-<?php echo $client['clientId'] ?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-<?php echo $client['clientId'] ?>">
                                <div class="panel-body panel-actions">
                                    <h4 class="panel-title">
                                        <a  class="btn btn-client">
                                            <div class="center-block">
                                                <i class="fa fa-shopping-cart fa-fw"></i>
                                                <?php echo $this->translate('Goods') ?>
                                                <span class="label label-info">
                                                    <?php echo $client['clientGoods'] + $client['clientBalance'] ?>
                                                </span>
                                            </div>
                                            <div class="center-block">
                                                <i class="fa fa-check fa-fw"></i>
                                                <?php echo $this->translate('Paid') ?>
                                                <span class="label label-default">
                                                    <?php echo $client['clientPaid'] ?>
                                                </span>
                                            </div>
                                            <div class="center-block">
                                                <i class="fa fa-warning fa-fw"></i>
                                                <?php echo $this->translate('Remaining') ?>
                                                <span class="label label-danger">
                                                    <?php echo $client['clientBalance'] + $client['clientGoods'] - $client['clientPaid'] ?>
                                                </span>
                                            </div>
                                        </a>
                                    </h4>

                                    <a href="<?php echo $this->baseUrl() . '/client/view/id/' . $client['clientId'] ?>" class="btn btn-primary">
                                        <?php   echo $this->translate('Statement Details'); 
                                                //$name = explode(' ', $client['clientName']);
                                                //echo $this->translate('Page') . ' ' . $name[0]; 
                                        ?>
                                    </a>
                                    <a href="<?php echo $this->baseUrl() .  '/statement/add/clientId/' . $client['clientId'] ?>" class="btn btn-success">
                                        <?php echo $this->translate('Add New Statement') ?>
                                    </a>
                                    <a href="<?php echo $this->baseUrl() .  '/payment/add/clientId/' . $client['clientId'] ?>" class="btn btn-info">
                                        <?php echo $this->translate('Make Payment') ?>
                                    </a>
                                </div>
                            </div>
                        </div>
                        
                    <?php }?>
                <?php } else { ?>
                    <div>
                        <p style="text-align: center"><?php echo $this->translate('There is no clients') ?></p>
                    </div>
                <?php }?>
            </div>
        </div>
        
        <div class="panel-footer">
            <div class="text-center">
                <?php if( isset($this->panelTitle) ){ ?>
                <a href="<?php echo $this->baseUrl() .  '/client/search' ?>" class="btn btn-default">
                    <?php echo $this->translate('Search Again') ?>
                </a>
                <?php } else {?>
                <nav>
                    <ul class="pagination pagination-sm">
                        <?php 
                        $totalPages = $this->totalPages;
                        $currentPage = $this->currentPage;
                        $prevPage = ($currentPage == 1)? $currentPage : $currentPage-1;
                        $nextPage = ($currentPage == $totalPages)? $currentPage: $currentPage+1;
                        ?>
                        <li class="<?php echo ($prevPage == $currentPage)? 'disabled' : '' ?>">
                            <a href="<?php echo ($prevPage == $currentPage)? '#' : $this->baseUrl('/client/group/id/'.$this->group['groupId'].'/page/'.$prevPage) ?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php for( $page = 1 ; $page <= $totalPages ; $page++ ){ ?>
                        <li class="<?php echo ($page == $currentPage)? 'active' : ''?>">
                            <a href="<?php echo $this->baseUrl('/client/group/id/'.$this->group['groupId'].'/page/'.$page) ?>">
                                <?php echo $page;?>
                            </a>
                        </li>
                        <?php }?>
                        <li class="<?php echo ($nextPage == $currentPage)? 'disabled' : '' ?>">
                            <a href="<?php echo ($nextPage == $currentPage)? '#' : $this->baseUrl('/client/group/id/'.$this->group['groupId'].'/page/'.$nextPage) ?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <?php }?>
            </div>
        </div>
        
    </div>
</div>