<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">
            <?php echo ( isset($this->panelTitle) ) ? $this->panelTitle : $this->group['groupName'] ?>
        </h3>
    </div>
    <div class="panel-body">
        <div  class="panel-scroll">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                        <!-- List Header -->
                        <div class="panel-client">
                            <div class="panel-heading" id="heading-0">
                                <h4 class="panel-title">
                                    <div  class="btn btn-client btn-client-heading">
                                        <strong><?php echo $this->translate('Client') ?></strong> 
                                        <span><i class="fa fa-bar-chart fa-fw"></i></span>
                                    </div>
                                </h4>
                            </div>
                        </div>
                
                <?php if(count($this->clients)) {?>
                    <?php foreach ($this->clients as $client) {?>
                
                        <div class="panel panel-client">
                            <div class="panel-heading" role="tab" id="heading-<?php echo $client['clientId'] ?>">
                                <h4 class="panel-title">
                                    <a  class="btn btn-default btn-client"
                                        data-toggle="collapse" 
                                        data-parent="#accordion" 
                                        href="#client-<?php echo $client['clientId'] ?>" 
                                        aria-expanded="true" 
                                        aria-controls="client-<?php echo $client['clientId'] ?>">
                                        
                                        <?php echo $client['clientName'] ?> 
                                        <span><strong><?php echo $client['clientPageNumber'] ?></strong> <i class="fa fa-file-text-o"></i></span>
                                        <div class="center-block">
                                            <i class="fa fa-shopping-cart fa-fw"></i>
                                            <?php echo $this->translate('Goods') ?>
                                            <span class="label label-default">
                                                <?php echo $client['clientGoods'] + $client['clientBalance'] ?>
                                            </span>
                                        </div>
                                        <div class="center-block">
                                            <i class="fa fa-check fa-fw"></i>
                                            <?php echo $this->translate('Paid') ?>
                                            <span class="label label-success">
                                                <?php echo $client['clientPaid'] ?>
                                            </span>
                                        </div>
                                        <div class="center-block">
                                            <i class="fa fa-warning fa-fw"></i>
                                            <?php echo $this->translate('Remaining') ?>
                                            <span class="label label-danger">
                                                <?php echo $client['clientBalance'] + $client['clientGoods'] - $client['clientPaid'] ?>
                                            </span>
                                        </div>
                                    </a>
                                </h4>
                            </div>
                            <div id="client-<?php echo $client['clientId'] ?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-<?php echo $client['clientId'] ?>">
                                <div class="panel-body">
                                    <div class="list-group-item">
                                        <!--<a href="<?php echo $this->baseUrl() . '/client/view/id/' . $client['clientId'] ?>#payments" class="btn btn-primary">
                                            <?php echo $this->translate('View Account') ?>
                                        </a>-->
                                        <a href="<?php echo $this->baseUrl() . '/client/view/id/' . $client['clientId'] ?>" class="btn btn-primary">
                                            <?php echo $this->translate('Statement Details') ?>
                                        </a>
                                        <a href="<?php echo $this->baseUrl() .  '/statement/add/clientId/' . $client['clientId'] ?>" class="btn btn-success">
                                            <?php echo $this->translate('Add New Statement') ?>
                                        </a>
                                        <a href="<?php echo $this->baseUrl() .  '/payment/add/clientId/' . $client['clientId'] ?>" class="btn btn-info">
                                            <?php echo $this->translate('Make Payment') ?>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    <?php }?>
                <?php } else { ?>
                    <div>
                        <p style="text-align: center"><?php echo $this->translate('There is no clients') ?></p>
                    </div>
                <?php }?>
            </div>
        </div>
        
        <?php if( isset($this->panelTitle) ){ ?>
        <div class="panel-footer">
            <div class="margin-20">
                <a href="<?php echo $this->baseUrl() .  '/client/search' ?>" class="btn btn-default">
                    <?php echo $this->translate('Search Again') ?>
                </a>
            </div>
        </div>
        <?php }?>
    </div>
</div>